apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3-auth
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: web
        image: socialcomputing/elas-official-backend-3-auth
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        - name: EUREKA_HOST_NAME
          value: $(BACKEND_1_SERVICE_REGISTRY_SERVICE)
        - name: EUREKA_PORT
          value: "8761"
        envFrom:
        - secretRef:
            name: admin
